import { GetServerSideProps, NextPage } from 'next'
import { AxiosResponse } from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import { fetchCategories } from '../http'
import { ICategory, ICollectionResponse } from '../types'
import { useEffect } from 'react'

const Home: NextPage = ({ }) => {

  useEffect
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>


        <h1 className='text-primary-dark'>
          Welcome to Daval's blog!
        </h1>

      </main>

    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {

  // categories
  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> = await fetchCategories()

  console.log('categories', categories)
  return {
    props: {
      categories: {
        items: categories.data
      }
    }
  }
}


export default Home